name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wishwell/backend
    steps:
    - uses: actions/checkout@v3
    - name: Set up PHP
      uses: shivammathur/setup-php@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    
    - name: Install dependencies
      working-directory: wishwell/backend
      run: composer install --prefer-dist --no-progress
    - name: Generate key
      working-directory: wishwell/backend/
      run: php artisan key:generate
      
    - name: Execute tests (Unit and Feature test) via PHPUnit
      working-directory: wishwell/backend
      run: vendor/bin/phpunit --stop-on-failure --coverage-php=coverage.php

    - name: Generate Coverage report
      working-directory: wishwell/backend
      run: |
          php coverage.php >> coverage.md
      env:
          XDEBUG_MODE: coverage

    - name: Create coverage artifact
      uses: actions/upload-artifact@v2
      with:
          name: coverage-report
          path: wishwell/backend/coverage.php
    
